### ISSUE TITLE
Use of bobsbg/yii2-oci2pdo

### ISSUE THREAD

**Issue by pedroriverove** [neutrinobg/yii2-oci2pdo#1]
Good day. How is it going?

They have some examples for using the bobsbg/yii2-oci2pdo extension as functions / procedures, LOBs, reference cursors, etc.

I am trying to execute a stored procedure in oracle. The SP is as follows:

## begin
                identidad.sp_consultaserialcita(prmserial => :prmserial, prmcur => :prmcur);
## end;

Where :prmserial is the input parameter and then returns a cursor that is :prmcur.

Thanks for the collaboration.

**Comment by neutrinobg** [comment]
Hello,

After executing the following piece of example code:
`$sql = "begin identidad.sp_consultaserialcita(prmserial => :prmserial, prmcur => :prmcur); end;";`
`$command = $connection->createCommand($sql);`
`$command->bindParam(":prmserial", $prmserial, PDO::PARAM_STR);`
`$command->bindParam(":prmcur", $result, OCI_B_CURSOR);`
`$rs = $command->queryAll();`

`$rs` has the record set of the returned rows from the cursor.

**Comment by pedroriverove** [comment]
Thanks, it works
